Update header.rs
Keats/jsonwebtoken pull request #384
Opened 2024-04-06 21:57 UTC by taylbm

add id to header struct to support WeatherKit JWT
https://developer.apple.com/documentation/weatherkitrestapi/request_authentication_for_weatherkit_rest_api
WeatherKit supports the JSON Web Token (JWT) specification, and allows you to pass statements and metadata called claims. For more information about JWT, see the [JWT specification](https://datatracker.ietf.org/doc/html/rfc7519). There are a variety of open source libraries available online for creating and signing JWT tokens. See [JWT.io](https://jwt.io/) for more information.

Construct a developer token as a JSON object with a header that contains the following information:

alg
The algorithm with which to sign the token. Set the value to ES256.

kid
A 10-character key identifier you obtain from your developer account.

id
An identifier that consists of your 10-character Team ID and Service ID, separated by a period.

2024-04-07 19:53 UTC, Keats commented
Can you link to a spec with the id field in headers for JWT? I've never seen it before, only `jti`

2024-04-10 22:43 UTC, taylbm commented
> Can you link to a spec with the id field in headers for JWT? I've never seen it before, only `jti`

yea I can't find it in the spec ... is it possible to specify custom header attributes?

2024-04-10 22:44 UTC, taylbm commented
Apple apparently thinks its a thing 😂 seems to be throwing a lot of devs for a loop!
```
{
    "alg": "ES256",
    "kid": "ABC123DEFG",
    "id": "DEF123GHIJ.com.example.weatherkit-client"
}
{
    "iss": "DEF123GHIJ",
    "iat": 1437179036,
    "exp": 1493298100,
    "sub": "com.example.weatherkit-client"
}
```

2024-04-10 22:47 UTC, taylbm commented
here's my fairly straightforward python implementation

```
  token_body = {
    "sub": WEATHERKIT_SERVICE_ID,
    "iss": WEATHERKIT_TEAM_ID,
    "exp": exp,
    "iat": now
  }
  token_headers = {
    "kid": WEATHERKIT_KID,
    "id": WEATHERKIT_FULL_ID
  }
  token = jwt.encode(token_body, WEATHERKIT_KEY, headers=token_headers, algorithm="ES256")

```

2024-04-11 09:15 UTC, Keats commented
> yea I can't find it in the spec ... is it possible to specify custom header attributes?

Not currently since we use a plain struct

2024-05-15 20:16 UTC, Keats requested changes

2024-05-15 20:16 UTC, Keats commented on Cargo.toml
> +authors = ["Vincent Prouillet <hello@vincentprouillet.com>", "Brandon Taylor <brandontaylor42@gmail.com"]
That field is only for the maintainers

2024-05-15 20:17 UTC, closed without merging